import React from "react";
import Footer from "./Footer";
import Testir from "./Testir";
const Testimonial=()=>
{
return <>
<div className="container-expand-lg testimoni">
    <div className="container">
        <div className="row mb-3">
        <Testir monial="Testimonials"  our="Don't just take our word. Here's what students from around the world have to say about us." This="This has honestly been the best help out of anything I've received in the last three months. I needed someone to be brutally honest with me and not sugarcoat any section of my application. I feel that now I have a clearer understanding on how to go about the next couple of days before my deadlines and that my chances of getting into Cornell will improve immensely. Thank you for the great insight!" sig="—K.R." fine="Ordered College App Review"
         Mahad="Mahad has been such a great help with this college admissions process. Not only did he do a great job explaining what all of my prompts were truly looking for, he also helped me brainstorm ideas to better connect my narrative to myself and how I wanted to portray myself to admissions officers. He even took a look at all my supplemental essays and gave me ideas on how to better approach each essay. I can confidently say that this call put me light years ahead of where I was a day ago. Thank you so much for the affordable and amazing service! I would recommend this service to anyone looking to make their college application/essay stand out." Really="Really helpful! I didn't realize that my second essay was a little bit cliche, so it was helpful to get the advice of someone outside of my bubble. Thank you so much, I'll definitely be back with a new Common App essay!"/>

        <Testir  This="This has honestly been the best help out of anything I've received in the last three months. I needed someone to be brutally honest with me and not sugarcoat any section of my application. I feel that now I have a clearer understanding on how to go about the next couple of days before my deadlines and that my chances of getting into Cornell will improve immensely. Thank you for the great insight!" sig="—K.R." fine="Ordered College App Review"
         Mahad="Mahad has been such a great help with this college admissions process. Not only did he do a great job explaining what all of my prompts were truly looking for, he also helped me brainstorm ideas to better connect my narrative to myself and how I wanted to portray myself to admissions officers. He even took a look at all my supplemental essays and gave me ideas on how to better approach each essay. I can confidently say that this call put me light years ahead of where I was a day ago. Thank you so much for the affordable and amazing service! I would recommend this service to anyone looking to make their college application/essay stand out." Really="Really helpful! I didn't realize that my second essay was a little bit cliche, so it was helpful to get the advice of someone outside of my bubble. Thank you so much, I'll definitely be back with a new Common App essay!"/>
        <Testir  This="This has honestly been the best help out of anything I've received in the last three months. I needed someone to be brutally honest with me and not sugarcoat any section of my application. I feel that now I have a clearer understanding on how to go about the next couple of days before my deadlines and that my chances of getting into Cornell will improve immensely. Thank you for the great insight!" sig="—K.R." fine="Ordered College App Review"
         Mahad="Mahad has been such a great help with this college admissions process. Not only did he do a great job explaining what all of my prompts were truly looking for, he also helped me brainstorm ideas to better connect my narrative to myself and how I wanted to portray myself to admissions officers. He even took a look at all my supplemental essays and gave me ideas on how to better approach each essay. I can confidently say that this call put me light years ahead of where I was a day ago. Thank you so much for the affordable and amazing service! I would recommend this service to anyone looking to make their college application/essay stand out." Really="Really helpful! I didn't realize that my second essay was a little bit cliche, so it was helpful to get the advice of someone outside of my bubble. Thank you so much, I'll definitely be back with a new Common App essay!"/>
        <Testir  This="This has honestly been the best help out of anything I've received in the last three months. I needed someone to be brutally honest with me and not sugarcoat any section of my application. I feel that now I have a clearer understanding on how to go about the next couple of days before my deadlines and that my chances of getting into Cornell will improve immensely. Thank you for the great insight!" sig="—K.R." fine="Ordered College App Review"
         Mahad="Mahad has been such a great help with this college admissions process. Not only did he do a great job explaining what all of my prompts were truly looking for, he also helped me brainstorm ideas to better connect my narrative to myself and how I wanted to portray myself to admissions officers. He even took a look at all my supplemental essays and gave me ideas on how to better approach each essay. I can confidently say that this call put me light years ahead of where I was a day ago. Thank you so much for the affordable and amazing service! I would recommend this service to anyone looking to make their college application/essay stand out." Really="Really helpful! I didn't realize that my second essay was a little bit cliche, so it was helpful to get the advice of someone outside of my bubble. Thank you so much, I'll definitely be back with a new Common App essay!"/>
        <Testir  This="This has honestly been the best help out of anything I've received in the last three months. I needed someone to be brutally honest with me and not sugarcoat any section of my application. I feel that now I have a clearer understanding on how to go about the next couple of days before my deadlines and that my chances of getting into Cornell will improve immensely. Thank you for the great insight!" sig="—K.R." fine="Ordered College App Review"
         Mahad="Mahad has been such a great help with this college admissions process. Not only did he do a great job explaining what all of my prompts were truly looking for, he also helped me brainstorm ideas to better connect my narrative to myself and how I wanted to portray myself to admissions officers. He even took a look at all my supplemental essays and gave me ideas on how to better approach each essay. I can confidently say that this call put me light years ahead of where I was a day ago. Thank you so much for the affordable and amazing service! I would recommend this service to anyone looking to make their college application/essay stand out." Really="Really helpful! I didn't realize that my second essay was a little bit cliche, so it was helpful to get the advice of someone outside of my bubble. Thank you so much, I'll definitely be back with a new Common App essay!"/>
        <Testir  This="This has honestly been the best help out of anything I've received in the last three months. I needed someone to be brutally honest with me and not sugarcoat any section of my application. I feel that now I have a clearer understanding on how to go about the next couple of days before my deadlines and that my chances of getting into Cornell will improve immensely. Thank you for the great insight!" sig="—K.R." fine="Ordered College App Review"
         Mahad="Mahad has been such a great help with this college admissions process. Not only did he do a great job explaining what all of my prompts were truly looking for, he also helped me brainstorm ideas to better connect my narrative to myself and how I wanted to portray myself to admissions officers. He even took a look at all my supplemental essays and gave me ideas on how to better approach each essay. I can confidently say that this call put me light years ahead of where I was a day ago. Thank you so much for the affordable and amazing service! I would recommend this service to anyone looking to make their college application/essay stand out." Really="Really helpful! I didn't realize that my second essay was a little bit cliche, so it was helpful to get the advice of someone outside of my bubble. Thank you so much, I'll definitely be back with a new Common App essay!"/>
        <Testir  This="This has honestly been the best help out of anything I've received in the last three months. I needed someone to be brutally honest with me and not sugarcoat any section of my application. I feel that now I have a clearer understanding on how to go about the next couple of days before my deadlines and that my chances of getting into Cornell will improve immensely. Thank you for the great insight!" sig="—K.R." fine="Ordered College App Review"
         Mahad="Mahad has been such a great help with this college admissions process. Not only did he do a great job explaining what all of my prompts were truly looking for, he also helped me brainstorm ideas to better connect my narrative to myself and how I wanted to portray myself to admissions officers. He even took a look at all my supplemental essays and gave me ideas on how to better approach each essay. I can confidently say that this call put me light years ahead of where I was a day ago. Thank you so much for the affordable and amazing service! I would recommend this service to anyone looking to make their college application/essay stand out." Really="Really helpful! I didn't realize that my second essay was a little bit cliche, so it was helpful to get the advice of someone outside of my bubble. Thank you so much, I'll definitely be back with a new Common App essay!"/>
        <Testir  This="This has honestly been the best help out of anything I've received in the last three months. I needed someone to be brutally honest with me and not sugarcoat any section of my application. I feel that now I have a clearer understanding on how to go about the next couple of days before my deadlines and that my chances of getting into Cornell will improve immensely. Thank you for the great insight!" sig="—K.R." fine="Ordered College App Review"
         Mahad="Mahad has been such a great help with this college admissions process. Not only did he do a great job explaining what all of my prompts were truly looking for, he also helped me brainstorm ideas to better connect my narrative to myself and how I wanted to portray myself to admissions officers. He even took a look at all my supplemental essays and gave me ideas on how to better approach each essay. I can confidently say that this call put me light years ahead of where I was a day ago. Thank you so much for the affordable and amazing service! I would recommend this service to anyone looking to make their college application/essay stand out." Really="Really helpful! I didn't realize that my second essay was a little bit cliche, so it was helpful to get the advice of someone outside of my bubble. Thank you so much, I'll definitely be back with a new Common App essay!"/>
        <Testir  This="This has honestly been the best help out of anything I've received in the last three months. I needed someone to be brutally honest with me and not sugarcoat any section of my application. I feel that now I have a clearer understanding on how to go about the next couple of days before my deadlines and that my chances of getting into Cornell will improve immensely. Thank you for the great insight!" sig="—K.R." fine="Ordered College App Review"
         Mahad="Mahad has been such a great help with this college admissions process. Not only did he do a great job explaining what all of my prompts were truly looking for, he also helped me brainstorm ideas to better connect my narrative to myself and how I wanted to portray myself to admissions officers. He even took a look at all my supplemental essays and gave me ideas on how to better approach each essay. I can confidently say that this call put me light years ahead of where I was a day ago. Thank you so much for the affordable and amazing service! I would recommend this service to anyone looking to make their college application/essay stand out." Really="Really helpful! I didn't realize that my second essay was a little bit cliche, so it was helpful to get the advice of someone outside of my bubble. Thank you so much, I'll definitely be back with a new Common App essay!"/>

        </div>

    </div>
    <Footer />

</div>



</>




}
export default Testimonial;